Moved desktop theme as a default dotfiles configurator theme
Add .muttrc and .muttrc.local to configuration symlinks
Exclude all gpg keys
Extract logic to dedicated functions
Fix naming in vars
Fix project tree structure into dotfiles configurator
Fix small issue while symlinking config files
Fix spaces in the beginning of printf commands
Fix typos
Improve creating secure password for mutt
Improve typos in output strings
Move settings/common into configuration directory
Removed themes directory
Rename muttrc into .muttrc
Renamed unused_plugins into unused_vim_plugins
Update installer of conky's configuration

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -24,8 +24,8 @@ __aborted__="${yellow}Action aborted${endColor}"
 # Current file variables
 __version__="2.3.0"
 PROJECT_NAME="The Egel dotfiles"
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"  #current path to file
-PROJECT_CONFIG_NAME='.dotfiles.config'
+CURRENT_FILE_DIRECTORY="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)" #current path to file
+PROJECT_CONFIG_NAME=".dotfiles.config"
 PROJECT_CONFIG_FILE=$HOME/${PROJECT_CONFIG_NAME}
 PROJECT_CONFIG_MISSING_VARIABLE_COUNTER=0
 PROJECT_INSTALL_DEFAULTS=
@@ -81,10 +81,10 @@ elif [ "$(uname)" == "Linux" ]; then
     esac
   fi
 elif [[ $(expr substr "$(uname -s)" 1 10) == "MINGW32_NT" && "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]]; then
-  printf "%b This program doesn't support Windows OS" "${__warning__}"
+  printf "%bThis program doesn't support Windows OS" "${__warning__}"
   exit 1;
 elif [[ $(expr substr "$(uname -s)" 1 10) =~ "CYGWIN" ]]; then
-  printf "%b This program doesn't support Cygwin project" "${__warning__}"
+  printf "%bThis program doesn't support Cygwin project" "${__warning__}"
   exit 1;
 fi
 
@@ -144,9 +144,9 @@ print_if_missing_variable() {
 
 print_last_command_status() {
   if [ $? -eq 0 ]; then
-    printf " %b\n" "${__done__}"
+    printf "↳ %b\n" "${__done__}"
   else
-    printf " %b\n" "${__error__}"
+    printf "↳ %b\n" "${__error__}"
   fi
 }
 
@@ -173,8 +173,8 @@ fix_file_or_directory_permission() {
 }
 
 do_copy_default_config_file() {
-  print_subsection "Copy default config file"
-  cp -fv "${DIR}/${PROJECT_CONFIG_NAME}" "${PROJECT_CONFIG_FILE}"
+  print_subsection "Copy dotfiles default config file"
+  cp -fv "${CURRENT_FILE_DIRECTORY}/${PROJECT_CONFIG_NAME}" "${PROJECT_CONFIG_FILE}"
   print_last_command_status
 }
 
@@ -182,8 +182,7 @@ do_set_config_vars() {
   # set some vars based on validate config
   PROJECT_REPOSITORY_DIR="${GIT_PROJECT_FOLDER_DIR}/${GIT_PROJECT_FOLDER_NAME}"
   PROJECT_LIB_DIR="$PROJECT_REPOSITORY_DIR/lib"
-  PROJECT_SETTINGS_COMMON_DIR="$PROJECT_REPOSITORY_DIR/settings/common"
-  PROJECT_SETTINGS_THEME_DIR="$PROJECT_REPOSITORY_DIR/settings/themes/$DOTFILES_THEME"
+  PROJECT_SETTINGS_COMMON_DIR="$PROJECT_REPOSITORY_DIR/configuration"
   PROJECT_CONFIGURATOR_FILE="$PROJECT_REPOSITORY_DIR/bin/$FILE_NAME"
 }
 
@@ -208,7 +207,7 @@ else
       # The installation process contains creating default config
       ;;
     *)
-      printf "%b Missing %s file.\n" "${__warning__}" "$PROJECT_CONFIG_FILE"
+      printf "%bMissing %s file.\n" "${__warning__}" "$PROJECT_CONFIG_FILE"
       printf "\n%b Do you want to copy default configuration file to fix it?" "${__question__}"
       read -r -p " (y/N) " _copy_default_configuration
       case $_copy_default_configuration in
@@ -251,42 +250,44 @@ remove_current_symlinks() {
   done
 }
 
-
-# Methods
+# check_program prints its name and given command
 check_program() {
-  _name=$1
-  _command=$2
-  printf "%b" "${purple}${_name}${endColor}"
-  eval "${_command}"
+  __name=$1
+  __command=$2
+  printf "%b" "${purple}${__name}${endColor}"
+  eval "${__command}"
 }
 
-# Making simlint to file/folder
+# make_symlink making a symlink to file or directory
 make_symlink() {
   __name=$1
   __if=$2 # input file (~/.dotfiles/.vimrc)
   __of=$3 # output file (~/.vimrc)
 
-  if [ -f "${__of}" ]; then
-    _type="file"
-  elif [ -d "${__of}" ]; then
-    _type="directory"
-  elif [ -L "${__of}" ]; then
-    _type="symlink"
-  fi
-
   printf "\n%b\n" "${purple}$__name${endColor}"
 
-  _renamed_file="$__of($DATE_UTC)"
-  if [[ ${_type} == "file" && ${_type} == "directory" ]]; then
-    printf "%b %b %s exist, so safely renaming it as %b\n" "${__info__}" "${purple}${__of}${endColor}" "${_type}" "${purple}${_renamed_file}${endColor}"
+  if [ -f "${__if}" ]; then
+    _type="file"
+  elif [ -d "${__if}" ]; then
+    _type="directory"
+  elif [ -L "${__if}" ]; then
+    _type="symlink"
+  else
+    printf "%bNo such file or directory like %b\n" "${__warning__}" "${purple}${__if}${endColor}"
+    return
+  fi
+
+  _renamed_file="${__of}(${DATE_UTC})"
+  if [[ -d ${__of} || -f ${__of} ]]; then
+    printf "%b%b %s exist, so safely renaming it as %b\n" "${__info__}" "${purple}${__of}${endColor}" "${_type}" "${purple}${_renamed_file}${endColor}"
     mv "$__of" "${_renamed_file}"
     print_last_command_status
   fi
 
-  if [ -z ${_type} ];then
-    printf "%b Symlinking %b\n" "${__info__}" "${purple}${__of}${endColor}"
+  if ! [[ -d ${__of} || -f ${__of} ]]; then
+    printf "%bSymlinking %b\n" "${__info__}" "${purple}${__of}${endColor}"
   else
-    printf "%b %b %s exist, so re-symlinking it\n" "${__info__}" "${purple}${__of}${endColor}" "${_type}"
+    printf "%b%b %s exist, so re-symlinking it\n" "${__info__}" "${purple}${__of}${endColor}" "${_type}"
   fi
 
   ln -sf "${__if}" "${__of}"
@@ -298,12 +299,18 @@ is_program_installed() {
   _install_script=$2
 
   if hash "${_program}" 2>/dev/null; then
-    printf "%b Program %b already exist at %s\n" "${__done__}" "${blue}${_program}${endColor}" "$(which ${_program})"
+    printf "%bProgram %b already exist at %s\n" "${__done__}" "${blue}${_program}${endColor}" "$(which ${_program})"
   else
     printf "Installing %b program. Please wait.\n" "${blue}${_program}${endColor}"
     eval "${_install_script}"
     print_last_command_status
-  fi;
+  fi
+}
+
+do_install_vim_plugin_manager() {
+  print_subsection "Installing Vim plugin manager (Neobundle)"
+  wget https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh -q -O - | bash
+  print_last_command_status
 }
 
 create_secure_mutt_passwords() {
@@ -430,7 +437,7 @@ do_install() {
   if [ -f "$PROJECT_CONFIG_FILE" ]; then
     printf "\n%b You already have %s config file at %b\n" "${__warning__}" "${FILE_NAME}" "${blue}${PROJECT_CONFIG_FILE}${endColor}"
     if [[ "$PROJECT_INSTALL_DEFAULTS" -ne 1 ]]; then # default: install -y
-      printf "%b Do you want to copy default configuration file to override current one?" "${__question__}"
+      printf "%bDo you want to copy default configuration file to override current one?" "${__question__}"
       read -r -p " (y/N) " _copy_default_configuration
     else
       _copy_default_configuration="n"
@@ -609,6 +616,7 @@ do_install() {
 
   print_subsection "Install Tmux Plugin Manager"
   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
+  print_last_command_status
 
   # change shell to ZSH + oh-my-zsh
   case $_install_zsh_and_ohmyzsh in
@@ -669,7 +677,7 @@ do_install() {
 
   # installing vim plugins (need to be after reconfiguration process of dotfiles configurator)
   print_subsection "Installing NeoBundle vim plugins"
-  printf "%b This operation might take some time.\n" "${__info__}"
+  printf "%bThis operation might take some time.\n" "${__info__}"
   eval "$HOME/.vim/bundle/neobundle.vim/bin/neoinstall"
   print_last_command_status
 
@@ -689,7 +697,7 @@ do_install() {
     brew update
     print_last_command_status
 
-    printf "%b Doctor brew\n" "${__info__}"
+    printf "%bDoctor brew\n" "${__info__}"
     brew doctor
     print_last_command_status
   fi
@@ -700,21 +708,21 @@ do_install() {
 
   printf "\n%b To finalize installation of ZSH shell, you need to reboot the system.\n" "${__info__}"
   if [[ "$PROJECT_INSTALL_DEFAULTS" -ne 1 ]]; then # default: install -y
-    printf "%b Would you like to do it now?" "${__question__}"
+    printf "%bWould you like to do it now?" "${__question__}"
     read -r -p " (y/N) " _reboot_now
   else
     _reboot_now="n"
   fi
 
   if [[ $_reboot_now =~ ^([yY]) ]]; then
-    printf "%b Now rebooting the system..." "${__info__}"
+    printf "%bNow rebooting the system..." "${__info__}"
     sudo reboot
   else
-    printf "%b Rebooting canceled by User\n" "${__info__}"
+    printf "%bRebooting canceled by User\n" "${__info__}"
   fi
 }
 
-do_fix_permissions() {
+do_fix_file_and_directories_permissions() {
   # According to http://superuser.com/q/215504/250469
   print_section "Fix permissions for fragile files and directories"
   fix_file_or_directory_permission "$HOME" 755
@@ -732,7 +740,7 @@ do_fix_permissions() {
 
 do_uninstall() {
   print_section "Uninstall ${PROJECT_NAME}"
-  printf "%b Are you sure you want to uninstall %s?" "${__question__}" "${PROJECT_NAME}"
+  printf "%bAre you sure you want to uninstall %s?" "${__question__}" "${PROJECT_NAME}"
   read -r -p " (y/N) " _uninstall_repo
   case $_uninstall_repo in
     y|Y)
@@ -743,7 +751,7 @@ do_uninstall() {
       exit 1;
       ;;
     *)
-      printf "%b Aborting uninstalling of ." "${__info__}" "${PROJECT_NAME}"
+      printf "%bAborting uninstalling of ." "${__info__}" "${PROJECT_NAME}"
       ;;
   esac
 }
@@ -762,11 +770,12 @@ do_reconfigure() {
   make_symlink ".tmux-osx.conf" "${PROJECT_SETTINGS_COMMON_DIR}/.tmux-osx.conf" "$HOME/.tmux-osx.conf"
   make_symlink ".tmux-linux.conf" "${PROJECT_SETTINGS_COMMON_DIR}/.tmux-linux.conf" "$HOME/.tmux-linux.conf"
   make_symlink ".tmux.conf" "${PROJECT_SETTINGS_COMMON_DIR}/.tmux.conf" "$HOME/.tmux.conf"
+  make_symlink ".tmux.conf.local" "${PROJECT_SETTINGS_COMMON_DIR}/.tmux.conf.local" "$HOME/.tmux.conf.local"
   make_symlink ".vim" "${PROJECT_SETTINGS_COMMON_DIR}/.vim" "$HOME/.vim"
   make_symlink ".vimrc" "${PROJECT_SETTINGS_COMMON_DIR}/.vimrc" "$HOME/.vimrc"
   make_symlink ".zshenv" "${PROJECT_SETTINGS_COMMON_DIR}/.zshenv" "$HOME/.zshenv"
   make_symlink ".zshrc" "${PROJECT_SETTINGS_COMMON_DIR}/.zshrc" "$HOME/.zshrc"
-  make_symlink ".zshrc.local" "${PROJECT_SETTINGS_THEME_DIR}/.zshrc.local" "$HOME/.zshrc.local"
+  make_symlink ".zshrc.local" "${PROJECT_SETTINGS_COMMON_DIR}/.zshrc.local" "$HOME/.zshrc.local"
   make_symlink ".mdlrc" "${PROJECT_SETTINGS_COMMON_DIR}/.mdlrc" "$HOME/.mdlrc"
   make_symlink ".gemrc" "${PROJECT_SETTINGS_COMMON_DIR}/.gemrc" "$HOME/.gemrc"
 
@@ -774,25 +783,20 @@ do_reconfigure() {
   make_symlink ".zprofile" "${PROJECT_SETTINGS_COMMON_DIR}/.zprofile" "$HOME/.zprofile"
 
   # Copy specyfic folders
-  case $DOTFILES_THEME in
-    desktop)
-      make_symlink ".conkyrc" "${PROJECT_LIB_DIR}/conky-themes/conky_seamod/.conkyrc" "$HOME/.conkyrc" # only for desktops (servers terminals not need GUI)
-      ;;
-    server)
-      ;;
-  esac
+  if [[ $IS_BASED_ON_UBUNTU_1604 || IS_ARCH  ]]; then
+    print_subsection "Installing Conky configuration"
+    make_symlink ".conkyrc" "${PROJECT_LIB_DIR}/conky-themes/conky_seamod/.conkyrc" "$HOME/.conkyrc" # only for desktops (servers terminals not need GUI)
+  fi
 
-  printf "\n\n%b\n" "${yellow}Checking NeoBundle:${endColor}"
-  wget https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh -q -O - | bash
-  print_last_command_status
+  do_install_vim_plugin_manager
 
   # fixing the permissions
-  do_fix_permissions
+  do_fix_file_and_directories_permissions
 }
 
 do_clean() {
   print_section "Clean ${PROJECT_NAME}"
-  printf "%b Are you sure you want to clean old %s symlinks?" "${__question__}" "${PROJECT_NAME}"
+  printf "%bAre you sure you want to clean old %s symlinks?" "${__question__}" "${PROJECT_NAME}"
   read -r -p " (y/N) " _cleaning_symlinks
   case $_cleaning_symlinks in
     y|Y)
@@ -802,14 +806,14 @@ do_clean() {
       exit 1;
       ;;
     *)
-      printf "%b Aborting cleaning of %s symlinks." "${__info__}" "${PROJECT_NAME}"
+      printf "%bAborting cleaning of %s symlinks." "${__info__}" "${PROJECT_NAME}"
       ;;
   esac
 }
 
 do_clean_all() {
   print_section "Clean ${PROJECT_NAME}"
-  printf "%b Are you sure you want to clean ALL %s symlinks?" "${__question__}" "${PROJECT_NAME}"
+  printf "%bAre you sure you want to clean ALL %s symlinks?" "${__question__}" "${PROJECT_NAME}"
   read -r -p " (y/N) " _cleaning_symlinks
   case $_cleaning_symlinks in
     y|Y)
@@ -820,7 +824,7 @@ do_clean_all() {
       exit 1;
       ;;
     *)
-      printf "%b Aborting cleaning of %s symlinks." "${__info__}" "${PROJECT_NAME}"
+      printf "%bAborting cleaning of %s symlinks." "${__info__}" "${PROJECT_NAME}"
       ;;
   esac
 }
@@ -833,12 +837,12 @@ do_backup() {
   print_section "Making backup of your private files"
 
   if [ ${#BACKUP_FILES[@]} -eq 0 ]; then
-    printf "%b There is no backup files set yet. Add BACKUP_FILES to %s\n" "${__warning__}" "${PROJECT_CONFIG_FILE}"
+    printf "%bThere is no backup files set yet. Add BACKUP_FILES to %s\n" "${__warning__}" "${PROJECT_CONFIG_FILE}"
     exit 1;
   fi
 
   BACKUP_DIR="${BACKUP_DIR}(${DATE_UTC})" # UTC but local
-  printf "%b Write backup directory (default path: '%s')\n" "${__info__}" "${BACKUP_DIR}"
+  printf "%bWrite backup directory (default path: '%s')\n" "${__info__}" "${BACKUP_DIR}"
   read -r -p " " _backup_dir
   if [ -n "${_backup_dir}" ]; then # if not empty
     BACKUP_DIR=${_backup_dir}
@@ -854,7 +858,7 @@ do_backup() {
     elif [ -f "${item}" ]; then # file
       cp -f "$item" "$BACKUP_DIR"
     fi
-    echo -e "Backup of $item completed ${__done__}"
+    printf "Backup of %s completed %b\n" "$item" "${__done__}"
   done
 
 }
@@ -883,7 +887,7 @@ case "$1" in
     create_secure_mutt_passwords
     ;;
   fix-permissions|-fp)
-    do_fix_permissions
+    do_fix_file_and_directories_permissions
     ;;
   uninstall)
     do_uninstall
@@ -906,5 +910,5 @@ case "$1" in
     ;;
 esac
 
-shift $((OPTIND - 1))
+shift "$((OPTIND - 1))"
 
