Replace Syntastic in favor of Vim-ALE
Update README with fixes from prettier fixer

Update vim-ale linter configs

Add changelog entry

Add shellcheck linter

Add code linter installer

Fix missing pip3 installation for ubuntu

Add remark markdown linter

Check markdown code in project

Update .remarkrc config

Add NodeJS to markdown travis test

Add prettier config

Update docs with new features

Add auto-fixer for typescript

Remove travis conf for markdown linting

Remove old syntastic config

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -272,6 +272,18 @@ check_program() {
   eval "${__command}"
 }
 
+# Checks if program exists in system or stops
+is_program_exist_in_system_or_die() {
+  __program_name=$1
+  result=$(command -v "${__program_name}")
+  if ! [ -x "$result" ]; then
+    printf "Missing program: %s\n" ${__program_name}
+    exit 1
+  else
+    printf "%s\n" $result
+  fi
+}
+
 # make_symlink making a symlink to file or directory
 make_symlink() {
   __name=$1
@@ -380,10 +392,12 @@ do_install_vim_from_source() {
       libluajit-5.1
     print_last_command_status
 
-    print_subsubsection "Install python2 and python3"
+    print_subsubsection "Install python2/pip and python3/pip3"
     sudo apt-get install -y \
       python-dev \
-      python3-dev
+      python-pip \
+      python3-dev \
+      python3-pip
     print_last_command_status
 
     print_subsubsection "Install ruby"
@@ -477,6 +491,63 @@ do_install_vim_from_source() {
     printf "download the .dmg file from\n"
     printf "https://github.com/macvim-dev/macvim/release\n\n"
   fi
+}
+
+# Install all linters used by Vim or IntelliJ
+do_install_code_linters() {
+  print_subsection "Install all linters used by Vim or IntelliJ"
+
+  print_subsubsection "Check if yarn is globally installed"
+  is_program_exist_in_system_or_die yarn
+
+  print_subsubsection "Check if python and pip are globally installed"
+  is_program_exist_in_system_or_die python   # any default python
+  is_program_exist_in_system_or_die python2  # python2
+  is_program_exist_in_system_or_die pip
+  is_program_exist_in_system_or_die python3  # python3
+  is_program_exist_in_system_or_die pip3
+
+  if $IS_MAC; then
+    print_subsubsection "Check if brew is globally installed"
+    is_program_exist_in_system_or_die brew
+  fi
+
+  print_subsubsection "Install Shell linting tools"
+  if $IS_MAC; then
+    brew install shellcheck
+  elif $IS_ARCH; then
+    pacman -S shellcheck
+  elif $IS_BASED_ON_UBUNTU_1604; then
+    sudo apt-get install -y shellcheck
+  fi
+
+  print_subsubsection "Install Python linting tools"
+  if $IS_MAC; then
+    pip install pylint
+  elif $IS_ARCH; then
+    pacman -S python2-pylint # if you live in the past: python2
+    pacman -S python-pylint  # if you live in the future: python3
+  elif $IS_BASED_ON_UBUNTU_1604; then
+    sudo apt-get install -y pylint
+  fi
+
+  print_subsubsection "Install Alex linter"
+  yarn global add \
+    alex
+
+  print_subsubsection "Install Markdown linting tools"
+  yarn global add \
+    remark-cli remark-preset-lint-recommended
+
+  print_subsubsection "Install Javascript and Typescript linting tools"
+  yarn global add \
+    eslint \
+    tslint \
+    typescript  # typescript for tslint
+
+  print_subsubsection "Install tools for beautifying the code"
+  yarn global add \
+    prettier # Prettify your code
 }
 
 create_secure_mutt_passwords() {
@@ -596,10 +667,11 @@ do_help() {
   printf "    clean-all, -ca\n"
   printf "        Clean all installation symlinks for current user home\n"
   printf "        directory (%s)\n\n" "$HOME"
-  printf "    install, -i [ vim ]\n"
+  printf "    install, -i [ vim, code-linters ]\n"
   printf "        Install and configure %s\n" "${PROJECT_CONFIG_FILE}"
   printf "        for current user.\n\n"
   printf "        vim - install Vim from source files.\n\n"
+  printf "        code-linters - install all linters used by Vim or IntelliJ.\n\n"
   printf "    list-config, -lc\n"
   printf "        List personal configuration file stored in %s\n" "${PROJECT_CONFIG_FILE}"
   printf "        for current user.\n\n"
@@ -832,6 +904,9 @@ do_install() {
     sudo systemctl enable NetworkManager-dispatcher.service
     sudo systemctl mask systemd-rfkill.service
   fi
+
+  # Install linters
+  do_install_code_linters
 
   # Install Ruby manager (rbenv)
   git clone https://github.com/rbenv/rbenv.git ~/.rbenv
@@ -1092,6 +1167,9 @@ case "$1" in
     case "$2" in
       vim)
         do_install_vim_from_source
+        ;;
+      code-linters)
+        do_install_code_linters
         ;;
       *)
         do_install
