Add Brewfile for osx configuration
Remove deprecated brew applinks command

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -582,31 +582,24 @@ do_install() {
   # copy dotfiles program to system binaries
   do_install_dotfiles_program_globally
 
+  # reconfigure dotfiles symlinks
+  do_reconfigure
 
   if $IS_MAC; then
     print_subsection "Installing brew - Mac OSX package manager"
     ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 
     print_subsection "Installing required programs"
-    brew install coreutils
-    brew install wget
-    brew install curl
-    brew install zsh
-    brew install tmux
-    brew install mutt
-    brew install lua
-    brew install python
-    brew install python3
-    brew install gnupg gnupg2
-    brew install shellcheck
-    brew install editorconfig
-
-    brew install vim --with-lua --with-python3
-    brew install macvim --with-lua --with-python3 --with-cscope --with-override-system-vim
-    brew install reattach-to-user-namespace # for copy from tmux to mac namespace
-
-    brew linkapps vim
-    brew linkapps macvim
+    # install programs from ~/Brewfile
+    if [[ -f "$HOME/Brewfile" ]]; then
+      # Brew has problem running outside of $HOME, so using subshell to
+      # encapsulate method to not interfere with current program.
+      # Enter the path before executing installation
+      (cd $HOME && brew bundle)
+    else
+      printf "%bNo Brewfile. Do 'dotfiles --reconfigure'\n" "${__error__}"
+      exit 1
+    fi
   elif $IS_BASED_ON_UBUNTU_1604; then
     print_subsection "Installing required software for further steps"
     sudo apt-get install -y software-properties-common
@@ -758,9 +751,6 @@ do_install() {
   print_subsection "Symlink honukai to oh-my-zsh themes"
   make_symlink "honukai.zsh-theme" "${PROJECT_LIB_DIR}/honukai-iterm-zsh/honukai.zsh-theme" "$HOME/.oh-my-zsh/themes/honukai.zsh-theme"
 
-  # call program reconfigure option
-  ${PROJECT_CONFIGURATOR_FILE} reconfigure
-
   print_subsection "Installing NeoBundle - Vim plugin manager"
   curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh
   print_last_command_status
@@ -853,7 +843,6 @@ do_uninstall() {
   esac
 }
 
-
 do_reconfigure() {
   print_section "Reconfigure ${PROJECT_NAME}"
   make_symlink ".aliases" "${PROJECT_SETTINGS_COMMON_DIR}/.aliases" "$HOME/.aliases"
@@ -879,10 +868,14 @@ do_reconfigure() {
   # $PATH variable not properly set in gvim/MacVim => http://stackoverflow.com/a/24542893/1977012
   make_symlink ".zprofile" "${PROJECT_SETTINGS_COMMON_DIR}/.zprofile" "$HOME/.zprofile"
 
-  # copy conky configuration
   if [[ $IS_BASED_ON_UBUNTU_1604 || $IS_ARCH  ]]; then
-    print_subsection "Installing Conky configuration"
+    print_subsection "Configuration specific for Linux"
     make_symlink ".conkyrc" "${PROJECT_LIB_DIR}/conky-themes/conky_seamod/.conkyrc" "$HOME/.conkyrc" # only for desktops (servers terminals not need GUI)
+  fi
+
+  if [[ $IS_MAC ]]; then
+    print_subsection "Configuration specific for OSX"
+    make_symlink "Brewfile" "${PROJECT_SETTINGS_COMMON_DIR}/Brewfile" "$HOME/Brewfile"
   fi
 
   # install vim plugin manager
