improve copying dotfiles configuration file

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -23,6 +23,7 @@ __done__="${green}✔ Done${endColor}"
 # Current file variables
 __version__="1.4.1"
 PROJECT_NAME="The Egel dotfiles"
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"  #current path to file
 PROJECT_CONFIG_NAME='.dotfiles.config'
 PROJECT_CONFIG_FILE=$HOME/${PROJECT_CONFIG_NAME}
 PROJECT_CONFIG_MISSING_VARIABLE_COUNTER=0
@@ -74,6 +75,21 @@ print_if_missing_variable() {
   fi
 }
 
+do_copy_default_config_file() {
+  print_subsection "Copy default config file"
+  cp -fv ${DIR}/${PROJECT_CONFIG_NAME} ${PROJECT_CONFIG_FILE} && echo -e "${__done__}"
+}
+
+
+do_set_config_vars() {
+  # set some vars based on validate config
+  PROJECT_REPOSITORY_DIR="${GIT_PROJECT_FOLDER_DIR}/${GIT_PROJECT_FOLDER_NAME}"
+  PROJECT_LIB_DIR="$PROJECT_REPOSITORY_DIR/lib"
+  PROJECT_SETTINGS_COMMON_DIR="$PROJECT_REPOSITORY_DIR/settings/common"
+  PROJECT_SETTINGS_THEME_DIR="$PROJECT_REPOSITORY_DIR/settings/themes/$DOTFILES_THEME"
+  PROJECT_CONFIGURATOR_FILE="$PROJECT_REPOSITORY_DIR/bin/$FILE_NAME"
+}
+
 # Load config variables for the project
 if [ -f $PROJECT_CONFIG_FILE ]; then
   source $PROJECT_CONFIG_FILE
@@ -86,17 +102,27 @@ if [ -f $PROJECT_CONFIG_FILE ]; then
     exit 1
   fi
 
-  # set some vars based on validate config
-  PROJECT_REPOSITORY_DIR="${GIT_PROJECT_FOLDER_DIR}/${GIT_PROJECT_FOLDER_NAME}"
-  PROJECT_LIB_DIR="$PROJECT_REPOSITORY_DIR/lib"
-  PROJECT_SETTINGS_COMMON_DIR="$PROJECT_REPOSITORY_DIR/settings/common"
-  PROJECT_SETTINGS_THEME_DIR="$PROJECT_REPOSITORY_DIR/settings/themes/$DOTFILES_THEME"
-  PROJECT_CONFIGURATOR_FILE="$PROJECT_REPOSITORY_DIR/bin/$FILE_NAME"
-  #echo ${PROJECT_TYPE_SETTINGS_THEME_DIR}
+  do_set_config_vars
 else
-  echo -e ${__error__} "Missing" $PROJECT_CONFIG_FILE "file."
-  echo "INFO: To fix this run: 'cp setup/$PROJECT_CONFIG_NAME $HOME' and adjust copied config file to your needs."
-  exit 1
+  case $1 in
+    install)
+      # empty because we want to pass it only for installation process.
+      # The installation process contains creating default config
+      ;;
+    *)
+      echo -e "${__warning__} Missing $PROJECT_CONFIG_FILE file."
+      echo -ne "${__info__}"
+      read -r -p " Do you want to copy default configuration file to fix it? (y/N) " _copy_default_configuration
+      case $_copy_default_configuration in
+        y|Y)
+          do_copy_default_config_file
+          ;;
+        *)
+          ;;
+      esac
+      exit 1
+      ;;
+  esac
 fi
 
 # Remove all old symlinks for dotfiles
@@ -177,23 +203,6 @@ print_section() {
 print_subsection() {
   _subsection=$1
   echo -e "\n${purple}--- ${_subsection}${endColor}"
-}
-
-is_config_exsist() {
-  if [ -f $PROJECT_CONFIG_FILE ]; then
-    source $PROJECT_CONFIG_FILE
-
-    if [ -z "$GIT_PROJECT_FOLDER_PATH" ]; then
-      print_missing_variable "GIT_PROJECT_FOLDER_NAME"
-      print_missing_variable "GIT_PROJECT_FOLDER_PATH"
-      exit 1
-    fi;
-
-  else
-    echo -e "${__error__} Missing $PROJECT_CONFIG_FILE file."
-    echo -e "${__info__} To fix this copy setup/${PROJECT_CONFIG_NAME} to ${PROJECT_CONFIG_FILE} and adjust copied sample config file to your needs."
-    exit 1
-  fi
 }
 
 is_program_installed() {
@@ -297,9 +306,32 @@ do_update() {
 
 do_install() {
   print_section "Installing ${PROJECT_NAME}"
-  echo "Ask for few questions to adjust installer for your preferences."
-  echo -ne "\n${__info__}"
-  read -r -p " Do you want to configure mutt with secured gpg password? ${PROJECT_NAME}? (y/N) " _configure_secure_mutt_gpg
+  echo -e "Ask for few questions to adjust configuration for your preferences:"
+
+  echo -ne "${__info__}"
+  read -r -p " Do you want to configure mutt with secured gpg password? (y/N) " _configure_secure_mutt_gpg
+
+  # ask only if config exsist and user run install again
+  if [ -f $PROJECT_CONFIG_FILE ]; then
+    echo -ne "${__info__} You already have dotfiles config file at $PROJECT_CONFIG_FILE\n"
+    read -r -p "Do you want to copy default configuration file to override the old one? (y/N) " _copy_default_configuration
+
+    # creating default config if set
+    case $_copy_default_configuration in
+      y|Y)
+        do_copy_default_config_file
+        . $PROJECT_CONFIG_FILE    # include/import config variables from file
+        do_set_config_vars        # recreate project vars on proper config paths
+        ;;
+      *)
+        ;;
+    esac
+  else
+    # force create default config file
+    do_copy_default_config_file
+    . $PROJECT_CONFIG_FILE    # include/import config variables from file
+    do_set_config_vars        # recreate project vars on proper config paths
+  fi
 
   # update dotfiles repository
   ${PROJECT_CONFIGURATOR_FILE} update
@@ -522,7 +554,7 @@ case "$1" in
     print_version
     ;;
   *)
-    echo -e "Nothing happened \xe2\x98\xba\nRun: '${FILE_NAME} --help' to print help menu for ${PROJECT_NAME} project." 1>&2;
+    echo -e "Nothing happened \xe2\x98\xba\nRun: '${FILE_NAME} --help' to print help menu." 1>&2;
     exit 1
     ;;
 esac
